---
- name: Configure webserver with nginx
  hosts: webservers
  become: yes
  tasks:
    - name: remove php
      apt: pkg=php5 state=absent
    - name: remove mysql
      apt: pkg=mysql-server state=absent
    - name: remove apache2
      apt: pkg=apache2 state=absent
    - name: install nginx
      apt: name=nginx update_cache=yes
    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default
    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link
    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
    - name: restart nginx
      service: name=nginx state=restarted
